name: Build
on: push
jobs:
  build:
    name: Build with Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [13, 14]
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - uses: stefanoeb/eslint-action@1.0.2
        name: ESLint
      - name: Install Modules
        run: sudo npm ci
      - name: Build
        run: sudo npm run build