name: Build
on: push
jobs:
  build:
    name: Build with Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 15]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install Modules
        run: sudo npm ci --unsafe-perm=true --allow-root
      - name: Build
        run: sudo npm run build