name: Tests
on: push
jobs:
  build:
    name: Test with Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [13, 14]
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Clone frontend
        uses: actions/checkout@v2.1.0
        with:
          path: frontend
      - name: Install frontend modules
        run: cd frontend && sudo npm ci --unsafe-perm=true --allow-root && cd ..
      - name: Clone core
        uses: actions/checkout@v2.1.0
        with:
          repository: 'cloud-cnc/core'
          path: core
      - name: Install core modules
        run: cd core && sudo npm ci --unsafe-perm=true --allow-root && cd ..
      - name: Install MongoDB
        run: sudo apt install -y mongodb
      - name: ESLint
        run: npx eslint frontend
      - name: Debug 1
        run: ls /home/runner/work/frontend/frontend
      - name: Debug 2
        run: ls /home/runner/work/frontend/frontend/frontend
      - uses: paambaati/codeclimate-action@v2.6.0
        name: Run Tests
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_REPORTER_ID }}
        with:
          coverageCommand: sudo npm run coverage